global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "quarkus-social"
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets:
          - localhost:8080
          - docker.host.internal:8080
          - quarkussocial:8080

#remote_write:
#  - url: "<Your Prometheus remote_write endpoint>"
#    basic_auth:
#      username: "<Your Grafana Username>"
#      password: "<Your Grafana API key>"